services:
  postgres:
    image: postgres:16
    container_name: madhupur_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: madhupur_rides
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seeds/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

volumes:
  postgres_data:
